const LIST_TYPE_HORIZONTAL = 'horizontal'
const LIST_TYPE_VERTICAL = 'vertical'

export const LIST_TYPES = {
  [LIST_TYPE_HORIZONTAL]: LIST_TYPE_HORIZONTAL,
  [LIST_TYPE_VERTICAL]: LIST_TYPE_VERTICAL,
}
