export const BUTTON_TYPES = {
  text: 'text',
  border: 'border',
  fill: 'fill',
}

export const SPECIAL_BUTTON_ADD = 'add'
export const SPECIAL_BUTTON_ADD_FILL = 'addFill'
export const SPECIAL_BUTTON_MINUS = 'minus'
export const SPECIAL_BUTTON_DELETE = 'delete'
export const SPECIAL_BUTTON_TEXT = 'text'
export const SPECIAL_BUTTON_ICON = 'icon'
export const SPECIAL_BUTTON_ARROW_LEFT = 'arrowLeft'
export const SPECIAL_BUTTON_ARROW_RIGHT = 'arrowRight'
export const SPECIAL_BUTTON_ATTACH = 'attach'
export const SPECIAL_BUTTON_EDIT = 'edit'
export const SPECIAL_BUTTON_DOWNLOAD = 'download'
export const SPECIAL_BUTTON_UPLOAD = 'upload'

export const BUTTON_SPECIAL_TYPES = {
  [SPECIAL_BUTTON_ADD]: SPECIAL_BUTTON_ADD,
  [SPECIAL_BUTTON_ADD_FILL]: SPECIAL_BUTTON_ADD_FILL,
  [SPECIAL_BUTTON_MINUS]: SPECIAL_BUTTON_MINUS,
  [SPECIAL_BUTTON_DELETE]: SPECIAL_BUTTON_DELETE,
  [SPECIAL_BUTTON_TEXT]: SPECIAL_BUTTON_TEXT,
  [SPECIAL_BUTTON_ICON]: SPECIAL_BUTTON_ICON,
  [SPECIAL_BUTTON_ARROW_LEFT]: SPECIAL_BUTTON_ARROW_LEFT,
  [SPECIAL_BUTTON_ARROW_RIGHT]: SPECIAL_BUTTON_ARROW_RIGHT,
  [SPECIAL_BUTTON_ATTACH]: SPECIAL_BUTTON_ATTACH,
  [SPECIAL_BUTTON_EDIT]: SPECIAL_BUTTON_EDIT,
  [SPECIAL_BUTTON_DOWNLOAD]: SPECIAL_BUTTON_DOWNLOAD,
  [SPECIAL_BUTTON_UPLOAD]: SPECIAL_BUTTON_UPLOAD,
}

export const BUTTON_COLORS = {
  red: 'red',
  blue: 'blue',
  white: 'white',
  gray: 'gray',
  orange: 'orange',
  green: 'green',
}
