export const CURRENCIES = {
  AED: { code: 'AED', number: '784', name: 'UAE Dirham', symbol: 'Dh' },
  AFN: { code: 'AFN', number: '971', name: 'Afghani', symbol: 'Af' },
  ALL: { code: 'ALL', number: '008', name: 'Lek', symbol: 'L' },
  AMD: { code: 'AMD', number: '051', name: 'Armenian Dram', symbol: '\u058F' },
  ANG: { code: 'ANG', number: '532', name: 'Netherlands Antillean Guilder', symbol: '\u0192' },
  AOA: { code: 'AOA', number: '973', name: 'Kwanza', symbol: 'Kz' },
  ARS: { code: 'ARS', number: '032', name: 'Argentine Peso', symbol: '$' },
  AUD: { code: 'AUD', number: '036', name: 'Australian Dollar', symbol: '$' },
  AWG: { code: 'AWG', number: '533', name: 'Aruban Guilder', symbol: '\u0192' },
  AZN: { code: 'AZN', number: '944', name: 'Azerbaijanian Manat', symbol: '\u20BC' },
  BAM: { code: 'BAM', number: '977', name: 'Convertible Mark', symbol: 'KM' },
  BBD: { code: 'BBD', number: '052', name: 'Barbados Dollar', symbol: '$' },
  BDT: { code: 'BDT', number: '050', name: 'Taka', symbol: '\u09F3' },
  BGN: { code: 'BGN', number: '975', name: 'Bulgarian Lev', symbol: 'лв' },
  BHD: { code: 'BHD', number: '048', name: 'Bahraini Dinar', symbol: 'BD' },
  BIF: { code: 'BIF', number: '108', name: 'Burundi Franc', symbol: '\u20A3' },
  BMD: { code: 'BMD', number: '060', name: 'Bermudian Dollar', symbol: '$' },
  BND: { code: 'BND', number: '096', name: 'Brunei Dollar', symbol: '$' },
  BOB: { code: 'BOB', number: '068', name: 'Boliviano', symbol: '$' },
  BRL: { code: 'BRL', number: '986', name: 'Brazilian Real', symbol: '$' },
  BSD: { code: 'BSD', number: '044', name: 'Bahamian Dollar', symbol: '$' },
  BTN: { code: 'BTN', number: '064', name: 'Ngultrum', symbol: 'Nu' },
  BWP: { code: 'BWP', number: '072', name: 'Pula', symbol: 'P' },
  BYN: { code: 'BYN', number: '933', name: 'Belarussian Ruble', symbol: 'Br' },
  BZD: { code: 'BZD', number: '084', name: 'Belize Dollar', symbol: '$' },
  CAD: { code: 'CAD', number: '124', name: 'Canadian Dollar', symbol: '$' },
  CDF: { code: 'CDF', number: '976', name: 'Congolese Franc', symbol: '\u20A3' },
  CHF: { code: 'CHF', number: '756', name: 'Swiss Franc', symbol: '\u20A3' },
  CLP: { code: 'CLP', number: '152', name: 'Chilean Peso', symbol: '$' },
  CNY: { code: 'CNY', number: '156', name: 'Yuan Renminbi', symbol: '\u00A5' },
  COP: { code: 'COP', number: '170', name: 'Colombian Peso', symbol: '$' },
  CRC: { code: 'CRC', number: '188', name: 'Costa Rican Colon', symbol: '\u20A1' },
  CUP: { code: 'CUP', number: '192', name: 'Cuban Peso', symbol: '$' },
  CVE: { code: 'CVE', number: '132', name: 'Cape Verde Escudo', symbol: '$' },
  CZK: { code: 'CZK', number: '203', name: 'Czech Koruna', symbol: 'K\u010D' },
  DJF: { code: 'DJF', number: '262', name: 'Djibouti Franc', symbol: '\u20A3' },
  DKK: { code: 'DKK', number: '208', name: 'Danish Krone', symbol: 'kr' },
  DOP: { code: 'DOP', number: '214', name: 'Dominican Peso', symbol: '$' },
  DZD: { code: 'DZD', number: '012', name: 'Algerian Dinar', symbol: 'DA' },
  EGP: { code: 'EGP', number: '818', name: 'Egyptian Pound', symbol: 'LE' },
  ERN: { code: 'ERN', number: '232', name: 'Nakfa', symbol: 'Nfk' },
  ETB: { code: 'ETB', number: '230', name: 'Ethiopian Birr', symbol: 'Br' },
  EUR: { code: 'EUR', number: '978', name: 'Euro', symbol: '\u20AC' },
  FJD: { code: 'FJD', number: '242', name: 'Fiji Dollar', symbol: '$' },
  FKP: { code: 'FKP', number: '238', name: 'Falkland Islands Pound', symbol: '\u00A3' },
  GBP: { code: 'GBP', number: '826', name: 'Pound Sterling', symbol: '\u00A3' },
  GEL: { code: 'GEL', number: '981', name: 'Lari', symbol: '\u20BE' },
  GHS: { code: 'GHS', number: '936', name: 'Ghana Cedi', symbol: '\u20B5' },
  GIP: { code: 'GIP', number: '292', name: 'Gibraltar Pound', symbol: '\u00A3' },
  GMD: { code: 'GMD', number: '270', name: 'Dalasi', symbol: 'D' },
  GNF: { code: 'GNF', number: '324', name: 'Guinea Franc', symbol: '\u20A3' },
  GTQ: { code: 'GTQ', number: '320', name: 'Quetzal', symbol: 'Q' },
  GYD: { code: 'GYD', number: '328', name: 'Guyana Dollar', symbol: '$' },
  HKD: { code: 'HKD', number: '344', name: 'Hong Kong Dollar', symbol: '$' },
  HNL: { code: 'HNL', number: '340', name: 'Lempira', symbol: 'L' },
  HRK: { code: 'HRK', number: '191', name: 'Kuna', symbol: 'Kn' },
  HTG: { code: 'HTG', number: '332', name: 'Gourde', symbol: 'G' },
  HUF: { code: 'HUF', number: '348', name: 'Forint', symbol: 'Ft' },
  IDR: { code: 'IDR', number: '360', name: 'Rupiah', symbol: 'Rp' },
  ILS: { code: 'ILS', number: '376', name: 'New Israeli Sheqel', symbol: '\u20AA' },
  INR: { code: 'INR', number: '356', name: 'Indian Rupee', symbol: '\u20B9' },
  IQD: { code: 'IQD', number: '368', name: 'Iraqi Dinar', symbol: 'ID' },
  IRR: { code: 'IRR', number: '364', name: 'Iranian Rial', symbol: 'IR' },
  ISK: { code: 'ISK', number: '352', name: 'Iceland Krona', symbol: 'kr' },
  JMD: { code: 'JMD', number: '388', name: 'Jamaican Dollar', symbol: '$' },
  JOD: { code: 'JOD', number: '400', name: 'Jordanian Dinar', symbol: 'JD' },
  JPY: { code: 'JPY', number: '392', name: 'Yen', symbol: '\u00A5' },
  KES: { code: 'KES', number: '404', name: 'Kenyan Shilling', symbol: 'KSh' },
  KGS: { code: 'KGS', number: '417', name: 'Som', symbol: 'с' },
  KHR: { code: 'KHR', number: '116', name: 'Riel', symbol: '\u17DB' },
  KMF: { code: 'KMF', number: '174', name: 'Comoro Franc', symbol: '\u20A3' },
  KPW: { code: 'KPW', number: '408', name: 'North Korean Won', symbol: '\uC6D0' },
  KRW: { code: 'KRW', number: '410', name: 'South Korean Won', symbol: '\u20A9' },
  KWD: { code: 'KWD', number: '414', name: 'Kuwaiti Dinar', symbol: 'KD' },
  KYD: { code: 'KYD', number: '136', name: 'Cayman Islands Dollar', symbol: '$' },
  KZT: { code: 'KZT', number: '398', name: 'Tenge', symbol: '\u20B8' },
  LAK: { code: 'LAK', number: '418', name: 'Kip', symbol: '\u20AD' },
  LBP: { code: 'LBP', number: '422', name: 'Lebanese Pound', symbol: '.\u0644.\u0644' },
  LKR: { code: 'LKR', number: '144', name: 'Sri Lanka Rupee', symbol: '\u20b9' },
  LRD: { code: 'LRD', number: '430', name: 'Liberian Dollar', symbol: '$' },
  LSL: { code: 'LSL', number: '426', name: 'Loti', symbol: 'L' },
  LYD: { code: 'LYD', number: '434', name: 'Libyan Dinar', symbol: 'LD' },
  MAD: { code: 'MAD', number: '504', name: 'Moroccan Dirham', symbol: 'Dh' },
  MDL: { code: 'MDL', number: '498', name: 'Moldovan Leu', symbol: 'L' },
  MGA: { code: 'MGA', number: '969', name: 'Malagasy Ariary', symbol: 'Ar.' },
  MKD: { code: 'MKD', number: '807', name: 'Denar', symbol: 'ден.' },
  MMK: { code: 'MMK', number: '104', name: 'Kyat', symbol: 'K' },
  MNT: { code: 'MNT', number: '496', name: 'Tugrik', symbol: '\u20AE' },
  MOP: { code: 'MOP', number: '446', name: 'Pataca', symbol: '$' },
  MRU: { code: 'MRU', number: '929', name: 'Ouguiya', symbol: 'UM' },
  MUR: { code: 'MUR', number: '480', name: 'Mauritius Rupee', symbol: '\u20b9' },
  MVR: { code: 'MVR', number: '462', name: 'Rufiyaa', symbol: 'Rf' },
  MWK: { code: 'MWK', number: '454', name: 'Kwacha', symbol: 'K' },
  MXN: { code: 'MXN', number: '484', name: 'Mexican Peso', symbol: '$' },
  MYR: { code: 'MYR', number: '458', name: 'Malaysian Ringgit', symbol: 'RM' },
  MZN: { code: 'MZN', number: '943', name: 'Mozambique Metical', symbol: 'MT' },
  NAD: { code: 'NAD', number: '516', name: 'Namibia Dollar', symbol: 'N$' },
  NGN: { code: 'NGN', number: '566', name: 'Naira', symbol: '\u20A6' },
  NIO: { code: 'NIO', number: '558', name: 'Cordoba Oro', symbol: '$' },
  NOK: { code: 'NOK', number: '578', name: 'Norwegian Krone', symbol: 'kr' },
  NPR: { code: 'NPR', number: '524', name: 'Nepalese Rupee', symbol: '\u20b9' },
  NZD: { code: 'NZD', number: '554', name: 'New Zealand Dollar', symbol: '$' },
  OMR: { code: 'OMR', number: '512', name: 'Rial Omani', symbol: 'RO' },
  PAB: { code: 'PAB', number: '590', name: 'Balboa', symbol: 'B/.' },
  PEN: { code: 'PEN', number: '604', name: 'Nuevo Sol', symbol: 'S/' },
  PGK: { code: 'PGK', number: '598', name: 'Kina', symbol: 'K' },
  PHP: { code: 'PHP', number: '608', name: 'Philippine Peso', symbol: '\u20B1' },
  PKR: { code: 'PKR', number: '586', name: 'Pakistan Rupee', symbol: '\u20b9' },
  PLN: { code: 'PLN', number: '985', name: 'Zloty', symbol: 'z\u0142' },
  PYG: { code: 'PYG', number: '600', name: 'Guarani', symbol: '\u20B2' },
  QAR: { code: 'QAR', number: '634', name: 'Qatari Rial', symbol: 'QR' },
  RON: { code: 'RON', number: '946', name: 'Romanian Leu', symbol: 'L' },
  RSD: { code: 'RSD', number: '941', name: 'Serbian Dinar', symbol: 'дин.' },
  RUB: { code: 'RUB', number: '643', name: 'Russian Ruble', symbol: '\u20BD' },
  RWF: { code: 'RWF', number: '646', name: 'Rwanda Franc', symbol: '\u20A3' },
  SAR: { code: 'SAR', number: '682', name: 'Saudi Riyal', symbol: 'SR' },
  SBD: { code: 'SBD', number: '090', name: 'Solomon Islands Dollar', symbol: '$' },
  SCR: { code: 'SCR', number: '690', name: 'Seychelles Rupee', symbol: '\u20b9' },
  SDG: { code: 'SDG', number: '938', name: 'Sudanese Pound', symbol: '\u00A3' },
  SEK: { code: 'SEK', number: '752', name: 'Swedish Krona', symbol: 'kr' },
  SGD: { code: 'SGD', number: '702', name: 'Singapore Dollar', symbol: '$' },
  SHP: { code: 'SHP', number: '654', name: 'Saint Helena Pound', symbol: '\u00A3' },
  SLL: { code: 'SLL', number: '694', name: 'Leone', symbol: 'Le' },
  SOS: { code: 'SOS', number: '706', name: 'Somali Shilling', symbol: 'S' },
  SRD: { code: 'SRD', number: '968', name: 'Surinam Dollar', symbol: '$' },
  SSP: { code: 'SSP', number: '728', name: 'South Sudanese Pound', symbol: 'SSP' },
  STN: { code: 'STN', number: '930', name: 'Dobra', symbol: 'Db' },
  SVC: { code: 'SVC', number: '222', name: 'El Salvador Colon', symbol: '\u20A1' },
  SYP: { code: 'SYP', number: '760', name: 'Syrian Pound', symbol: 'S\u00A3' },
  SZL: { code: 'SZL', number: '748', name: 'Lilangeni', symbol: 'L' },
  THB: { code: 'THB', number: '764', name: 'Baht', symbol: '\u0E3F' },
  TJS: { code: 'TJS', number: '972', name: 'Somoni', symbol: 'с.' },
  TMT: { code: 'TMT', number: '934', name: 'Turkmenistan New Manat', symbol: 'm' },
  TND: { code: 'TND', number: '788', name: 'Tunisian Dinar', symbol: 'TD' },
  TOP: { code: 'TOP', number: '776', name: 'Pa’anga', symbol: '$' },
  TRY: { code: 'TRY', number: '949', name: 'Turkish Lira', symbol: '\u20BA' },
  TTD: { code: 'TTD', number: '780', name: 'Trinidad and Tobago Dollar', symbol: '$' },
  TWD: { code: 'TWD', number: '901', name: 'New Taiwan Dollar', symbol: 'NT$' },
  TZS: { code: 'TZS', number: '834', name: 'Tanzanian Shilling', symbol: 'TSh' },
  UAH: { code: 'UAH', number: '980', name: 'Hryvnia', symbol: '\u20B4' },
  UGX: { code: 'UGX', number: '800', name: 'Uganda Shilling', symbol: 'USh' },
  USD: { code: 'USD', number: '840', name: 'US Dollar', symbol: '$' },
  UYU: { code: 'UYU', number: '858', name: 'Peso Uruguayo', symbol: '$' },
  UZS: { code: 'UZS', number: '860', name: 'Uzbekistan Sum', symbol: 'с\u045Eм' },
  VES: { code: 'VES', number: '928', name: 'Bolívar Soberano', symbol: 'Bs. S.' },
  VND: { code: 'VND', number: '704', name: 'Dong', symbol: '\u20AB' },
  VUV: { code: 'VUV', number: '548', name: 'Vatu', symbol: 'Vt' },
  WST: { code: 'WST', number: '882', name: 'Tala', symbol: '$' },
  XAF: { code: 'XAF', number: '950', name: 'CFA Franc BEAC', symbol: '\u20A3' },
  XCD: { code: 'XCD', number: '951', name: 'East Caribbean Dollar', symbol: '$' },
  XOF: { code: 'XOF', number: '952', name: 'CFA Franc BCEAO', symbol: '\u20A3' },
  XPF: { code: 'XPF', number: '953', name: 'CFP Franc', symbol: '\u20A3' },
  YER: { code: 'YER', number: '886', name: 'Yemeni Rial', symbol: 'YR' },
  ZAR: { code: 'ZAR', number: '710', name: 'Rand', symbol: 'R' },
  ZMW: { code: 'ZMW', number: '967', name: 'Zambian Kwacha', symbol: 'K' },
  ZWL: { code: 'ZWL', number: '932', name: 'Zimbabwe Dollar', symbol: 'Z$' },
}

export const CURRENCY_CODES = Object.keys(CURRENCIES).reduce((memo, curr) => ({
  ...memo,
  [curr.toLowerCase()]: curr,
}), {})

export const CURRENCY_SIGN_TYPE = {
  code: 'code',
  name: 'name',
  symbol: 'symbol',
}
