export const LOADING_INDICATOR_TYPE_TEXT = 'text'
export const LOADING_INDICATOR_TYPE_SPINNER = 'spinner'
export const LOADING_INDICATOR_TYPE_CIRCLE = 'circle'

export const LOADING_INDICATOR_TYPES = {
  [LOADING_INDICATOR_TYPE_TEXT]: LOADING_INDICATOR_TYPE_TEXT,
  [LOADING_INDICATOR_TYPE_SPINNER]: LOADING_INDICATOR_TYPE_SPINNER,
  [LOADING_INDICATOR_TYPE_CIRCLE]: LOADING_INDICATOR_TYPE_CIRCLE,
}
