export const BACK_BUTTON_BUTTON = 'button'
export const BACK_BUTTON_FLOATING = 'floating'

export const BACK_BUTTON_TYPES = {
  [BACK_BUTTON_BUTTON]: BACK_BUTTON_BUTTON,
  [BACK_BUTTON_FLOATING]: BACK_BUTTON_FLOATING,
}
