export const HEADER_TYPE_PRIMARY = 'primary'
export const HEADER_TYPE_SECONDARY = 'secondary'
export const HEADER_TYPE_LEFT_ALIGNED = 'left'
export const HEADER_TYPE_VERTICAL = 'vertical'

export const HEADER_TYPES = {
  [HEADER_TYPE_PRIMARY]: HEADER_TYPE_PRIMARY,
  [HEADER_TYPE_SECONDARY]: HEADER_TYPE_SECONDARY,
  [HEADER_TYPE_LEFT_ALIGNED]: HEADER_TYPE_LEFT_ALIGNED,
  [HEADER_TYPE_VERTICAL]: HEADER_TYPE_VERTICAL,
}

export const MIN_MENU_RENDERERS = 2
