export const LIST_TYPE_LOAD_MORE_BUTTON = 'loadMoreButton'
export const LIST_TYPE_INFINITE_SCROLL = 'infiniteScroll'

export const LIST_TYPES = {
  [LIST_TYPE_LOAD_MORE_BUTTON]: LIST_TYPE_LOAD_MORE_BUTTON,
  [LIST_TYPE_INFINITE_SCROLL]: LIST_TYPE_INFINITE_SCROLL,
}
